import { Geist, Geist_Mono, Manrope, Syne,Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable : "--font-poppins-sans",
  subsets : ['latin'],
  weight : ['100','200','300','400','500','600','700','800','900']
})
const syne = Syne({
  variable : "--font-syne-sans",
  subsets : ['latin'],
})
const manrope = Manrope({
  variable : "--font-manrope-sans",
  subsets : ["latin"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${syne.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
